# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: BATCH Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_DRIVER: ${{ secrets.SPRING_DATASOURCE_DRIVER}}
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL}}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME}}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD}}
      PROJECT_NAME: my-item-stock
      SUBPROJECT_NAME: -batch
      PROJECT_VERSION: 0.0.1-SNAPSHOT
      ZIP_NAME: $PROJECT_NAME$SUBPROJECT_NAME-$PROJECT_VERSION.zip

    steps:
      - name: Source Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set AWS confidentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Check Public IP of Github Instance
        run: |
          export PUBLIC_IP=`curl -s icanhazip.com`
          echo $PUBLIC_IP

      - name: Set SG Inbound enable for public ip
        run: >
          aws ec2 authorize-security-group-ingress
          --group-id sg-073a42921509412a8
          --protocol tcp
          --port 3306
          --cidr $PUBLIC_IP/32

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Make zip file
        run: zip -r $ZIP_NAME . -x ./.gradle/\* # 프로젝트 전체를 묶어야 한다

      - name: Upload Zip to S3
        run: >
          aws s3 cp
          --region ap-northeast-2
          $ZIP_NAME s3://$PROJECT_NAME

      - name : Deploy from S3 with CodeDeploy
        run : >
          aws deploy create-deployment
          --application-name $PROJECT_NAME$SUBPROJECT_NAME
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name dg-$PROJECT_NAME$SUBPROJECT_NAME
          --s3-location bucket=$PROJECT_NAME,bundleType=zip,key=$ZIP_NAME


#    - name: Deploy from Github Directly with CodeDeploy
#      run: >
#        aws deploy create-deployment
#        --application-name my-item-stock
#        --deployment-config-name CodeDeployDefault.AllAtOnce
#        --deployment-group-name my-item-stock-dg
#        --description "My-Item-Stock PRD Deployment"
#        --github-location repository=${{ github.repository }},commitId=${{ github.sha }}